// <auto-generated />
using System;
using Forge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forge.Api.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    [Migration("20260127173327_RemoveRepositoryIsDefault")]
    partial class RemoveRepositoryIsDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Forge.Api.Data.Entities.AgentArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInputReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanInputRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProducedInState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubtaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubtaskId", "CreatedAt")
                        .HasDatabaseName("IX_AgentArtifacts_Subtask_CreatedAt");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("IX_AgentArtifacts_Task_CreatedAt");

                    b.HasIndex("TaskId", "ProducedInState")
                        .HasDatabaseName("IX_AgentArtifacts_Task_State");

                    b.ToTable("AgentArtifacts");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.HumanGateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubtaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubtaskId");

                    b.HasIndex("TaskId", "Status")
                        .HasDatabaseName("IX_HumanGates_Task_Status");

                    b.ToTable("HumanGates");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Read");

                    b.HasIndex("TaskId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RepositoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGitRepository")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Repositories_Active");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_Repositories_Path");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RollbackRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionTakenJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreservedArtifactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryOptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateBeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubtaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubtaskId");

                    b.HasIndex("TaskId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_RollbackRecords_Timestamp");

                    b.ToTable("RollbackRecords");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.SubtaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImplementationRetries")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SimplificationIterations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Subtasks_Status");

                    b.HasIndex("ParentTaskId", "ExecutionOrder")
                        .HasDatabaseName("IX_Subtasks_Parent_Order");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedFramework")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPendingGate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HumanInputReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanInputRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImplementationRetries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedNextState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimplificationIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Tasks_ParentId");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("IX_Tasks_RepositoryId");

                    b.HasIndex("State", "IsPaused", "AssignedAgentId")
                        .HasDatabaseName("IX_Tasks_Schedulable");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Timestamp")
                        .HasDatabaseName("IX_TaskLogs_Task_Timestamp");

                    b.ToTable("TaskLogs");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.AgentArtifactEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.SubtaskEntity", "Subtask")
                        .WithMany("Artifacts")
                        .HasForeignKey("SubtaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany("Artifacts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.HumanGateEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.SubtaskEntity", "Subtask")
                        .WithMany("HumanGates")
                        .HasForeignKey("SubtaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany("HumanGates")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RollbackRecordEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.SubtaskEntity", "Subtask")
                        .WithMany()
                        .HasForeignKey("SubtaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subtask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.SubtaskEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Forge.Api.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("Tasks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskLogEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RepositoryEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.SubtaskEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("HumanGates");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Children");

                    b.Navigation("HumanGates");

                    b.Navigation("Logs");

                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
