// <auto-generated />
using System;
using Forge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forge.Api.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    partial class ForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Forge.Api.Data.Entities.AgentArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInputReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanInputRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProducedInBacklogState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProducedInState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId", "CreatedAt")
                        .HasDatabaseName("IX_AgentArtifacts_BacklogItem_CreatedAt");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("IX_AgentArtifacts_Task_CreatedAt");

                    b.HasIndex("TaskId", "ProducedInState")
                        .HasDatabaseName("IX_AgentArtifacts_Task_State");

                    b.ToTable("AgentArtifacts");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.BacklogItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedTaskCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedFramework")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPendingGate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HumanInputReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanInputRequested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RefiningIterations")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("IX_BacklogItems_RepositoryId");

                    b.HasIndex("State", "IsPaused", "AssignedAgentId")
                        .HasDatabaseName("IX_BacklogItems_Schedulable");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.HumanGateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId", "Status")
                        .HasDatabaseName("IX_HumanGates_BacklogItem_Status");

                    b.HasIndex("TaskId", "Status")
                        .HasDatabaseName("IX_HumanGates_Task_Status");

                    b.ToTable("HumanGates");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Read");

                    b.HasIndex("TaskId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RepositoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGitRepository")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Repositories_Active");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_Repositories_Path");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RollbackRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionTakenJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreservedArtifactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryOptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateBeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("TaskId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_RollbackRecords_Timestamp");

                    b.ToTable("RollbackRecords");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedFramework")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPendingGate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HumanInputReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanInputRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImplementationRetries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedNextState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimplificationIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("IX_Tasks_RepositoryId");

                    b.HasIndex("BacklogItemId", "ExecutionOrder")
                        .HasDatabaseName("IX_Tasks_BacklogItem_Order");

                    b.HasIndex("State", "IsPaused", "AssignedAgentId")
                        .HasDatabaseName("IX_Tasks_Schedulable");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId", "Timestamp")
                        .HasDatabaseName("IX_TaskLogs_BacklogItem_Timestamp");

                    b.HasIndex("TaskId", "Timestamp")
                        .HasDatabaseName("IX_TaskLogs_Task_Timestamp");

                    b.ToTable("TaskLogs");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.AgentArtifactEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.BacklogItemEntity", "BacklogItem")
                        .WithMany("Artifacts")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany("Artifacts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BacklogItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.BacklogItemEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("BacklogItems")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.HumanGateEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.BacklogItemEntity", "BacklogItem")
                        .WithMany("HumanGates")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany("HumanGates")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BacklogItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.BacklogItemEntity", "BacklogItem")
                        .WithMany()
                        .HasForeignKey("BacklogItemId");

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BacklogItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RollbackRecordEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.BacklogItemEntity", "BacklogItem")
                        .WithMany()
                        .HasForeignKey("BacklogItemId");

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BacklogItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.BacklogItemEntity", "BacklogItem")
                        .WithMany("Tasks")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forge.Api.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskLogEntity", b =>
                {
                    b.HasOne("Forge.Api.Data.Entities.BacklogItemEntity", "BacklogItem")
                        .WithMany("Logs")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Forge.Api.Data.Entities.TaskEntity", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BacklogItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.BacklogItemEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("HumanGates");

                    b.Navigation("Logs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.RepositoryEntity", b =>
                {
                    b.Navigation("BacklogItems");
                });

            modelBuilder.Entity("Forge.Api.Data.Entities.TaskEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("HumanGates");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
